# Generated by Django 4.2.7 on 2024-01-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='created_by',
            new_name='user',
        ),
    ]
